export default [
  {
    "id": "ref_exam",
    "name": "Exam Browser",
    "description": "Konfigurasi Browser Ujian",
    "category": "Browser",
    "type": "browser",
  },
  {
    "id": "ref_navigation",
    "name": "Header",
    "description": "Konfigurasi Navigasi Halaman Utama",
    "category": "Navigation",
    "type": "navigation",
  },
  {
    "id": "ref_footer",
    "name": "Footer",
    "description": "Konfigurasi Footer Halaman Utama",
    "category": "Navigation",
    "type": "navigation",
  },
  {
    "id": "ref_education",
    "name": "Jenjang Pendidikan",
    "description": "Konfigurasi Daftar Jenjang Pendidikan",
    "category": "Edukasi",
    "type": "percent",
  },
  {
    "id": "ref_certification",
    "name": "Keahlian / Sertifikasi",
    "description": "Konfigurasi Daftar Keahlian",
    "category": "Edukasi",
    "type": "percent",
  },
  {
    "id": "ref_departement",
    "name": "Jurusan",
    "description": "Konfigurasi Daftar Jurusan",
    "category": "Edukasi",
    "type": "percent",
  },
  {
    "id": "ref_performance",
    "name": "Penilaian Kinerja",
    "description": "Konfigurasi Penilaian Kinerja",
    "category": "Kinerja",
    "type": "percent",
  },
  {
    "id": "ref_experience",
    "name": "Pengalaman Kerja",
    "description": "Konfigurasi Pengalaman Kerja",
    "category": "Pengalaman",
    "type": "percent",
  },
  {
    "id": "ref_age",
    "name": "Umur",
    "description": "Konfigurasi Kategori Umur",
    "category": "Profil",
    "type": "percent",
  },
  {
    "id": "ref_vacancy",
    "name": "Tipe Lowongan",
    "description": "Konfigurasi Tipe Lowongan",
    "category": "Lowongan",
    "type": "point",
  },
]
